before_script:
    # Decrypt server key
    - openssl enc -aes-256-cbc -md sha256 -salt -d -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD -pbkdf2
    # Install jq, a json parsing library
    - apt update && apt -y install jq
    # Setup SFDX environment variables
    # https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_env_variables.htm
    - export SALESFORCE_CLI_URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    - export SFDX_AUTOUPDATE_DISABLE=false
    - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
    - export SFDX_DOMAIN_RETRY=600
    - export SFDX_LOG_LEVEL=DEBUG
    # Install Salesforce CLI
    - mkdir sfdx
    - wget -qO- $SALESFORCE_CLI_URL | tar xJ -C sfdx --strip-components 1
    - './sfdx/install'
    - export PATH=./sfdx/$(pwd):$PATH
    # Output CLI version and plug-in information
    # - sfdx update
    # - sfdx --version
    - value=$(<deployTheseFiles.txt)
    - echo "$value"
    - ls
    - mkdir deploy
    - cp $value ./deploy -r
    # - sfdx plugins --core


Validate in SB:
  only:
      refs:
        - sandbox
  stage: test
  when: manual
  allow_failure: false
  script:
  - sfdx force:source:convert -r ./deploy/ -d ./deploy/mdformat
  - sfdx force:auth:jwt:grant --clientid $SBCLIENTID --jwtkeyfile assets/server.key --username $SBUSER --setdefaultdevhubusername --instanceurl $SBURL
  - sfdx force:mdapi:deploy -c -u $SBUSER -d deploy/mdformat -l NoTestRun --wait 10


Deploy in SB:
  only:
      refs:
        - sandbox
  stage: deploy
  when: manual
  script:
  - sfdx force:source:convert -r ./deploy/ -d ./deploy/mdformat
  - sfdx force:auth:jwt:grant --clientid $SBCLIENTID --jwtkeyfile assets/server.key --username $SBUSER --setdefaultdevhubusername --instanceurl $SBURL
  - sfdx force:mdapi:deploy -u $SBUSER -d deploy/mdformat -l NoTestRun --wait 10

Validate in Production:
  only:
      refs:
        - master
  stage: test
  when: manual
  allow_failure: false
  script:
  - sfdx force:source:convert -r ./deploy/ -d ./deploy/mdformat
  - sfdx force:auth:jwt:grant --clientid $PRODCLIENTID --jwtkeyfile assets/server.key --username $PRODUSER --setdefaultdevhubusername --instanceurl $PRODURL
  - sfdx force:mdapi:deploy -c -u $PRODUSER -d deploy/mdformat -l RunLocalTests --wait 10


Deploy in Production:
  only:
      refs:
        - master
  stage: deploy
  when: manual
  script:
  - sfdx force:source:convert -r ./deploy/ -d ./deploy/mdformat
  - sfdx force:auth:jwt:grant --clientid $PRODCLIENTID --jwtkeyfile assets/server.key --username $PRODUSER --setdefaultdevhubusername --instanceurl $PRODURL
  - sfdx force:mdapi:deploy -u $PRODUSER -d deploy/mdformat -l RunLocalTests --wait 10

# RunLocalTests RunAllTestsInOrg RunSpecifiedTests NoTestRun